<?php

$books = [
    'Silver Serpent' => [
        'id' => '12345',
        'author' => 'Frank Novelist',
        'color' => 'Silver',
        'genre' => 'Fantasy',
        'released' => '1922',
    ],
    'Crimson Moonrise' => [
        'id' => '54321',
        'author' => 'Grace Writer',
        'color' => 'Red',
        'genre' => 'Mystery',
        'released' => '1955',
    ],
    'Emerald Echoes' => [
        'id' => '67890',
        'author' => 'Henry Wordsmith',
        'color' => 'Green',
        'genre' => 'Romance',
        'released' => '1912',
    ],
    'Golden Key' => [
        'id' => '89797',
        'author' => 'Isabel Storyteller',
        'color' => 'Yellow',
        'genre' => 'Adventure',
        'released' => '1992',
    ],
    'Sapphire Shadows' => [
        'id' => '23556',
        'author' => 'Jack Author',
        'color' => 'Blue',
        'genre' => 'Thriller',
        'released' => '1998',
    ],
    'Scarlet Secrets' => [
        'id' => '56341',
        'author' => 'Karine Novelist',
        'color' => 'Red',
        'genre' => 'Mystery',
        'released' => '2008',
    ],
    'Bronze Blade' => [
        'id' => '32545',
        'author' => 'Liam Writer',
        'color' => 'teal',
        'genre' => 'Historical Fiction',
        'released' => '2010',
    ],
    'Violet Vendetta' => [
        'id' => '93275',
        'author' => 'Mia Wordsmith',
        'color' => 'Purple',
        'genre' => 'Crime',
        'released' => '1988',
    ],
    'Enchanted Forest' => [
        'id' => '23564',
        'author' => 'Nathan Storyteller',
        'color' => 'Green',
        'genre' => 'Fantasy',
        'released' => '1988',
    ],
    'Ruby Redemption' => [
        'id' => '12456',
        'author' => 'Olivia Author',
        'color' => 'Red',
        'genre' => 'Romance',
        'released' => '1942',
    ],
    'Midnight Murders' => [
        'id' => '32675',
        'author' => 'Patrick Novelist',
        'color' => 'navy',
        'genre' => 'Mystery',
        'released' => '2002',
    ],
    'Aqua Odyssey' => [
        'id' => '65488',
        'author' => 'Quincy Writer',
        'color' => 'Aqua',
        'genre' => 'Adventure',
        'released' => '2014',
    ],
    'Copper Chronicles' => [
        'id' => '23298',
        'author' => 'Rachel Wordsmith',
        'color' => 'violet',
        'genre' => 'Fantasy',
        'released' => '2020',
    ],
    'Topaz Treasures' => [
        'id' => '53489',
        'author' => 'Samuel Storyteller',
        'color' => 'Orange',
        'genre' => 'Adventure',
        'released' => '2019',
    ]
];
