<?php

$books = [
    'Silver Serpent' => [
        'id' => '12345',
        'author' => 'Frank Novelist',
        'color' => 'Silver',
        'genre' => 'Fantasy',
        'released' => '1922',
        'height' => '248px',
    ],
    'Crimson Moonrise' => [
        'id' => '54321',
        'author' => 'Grace Writer',
        'color' => 'Red',
        'genre' => 'Mystery',
        'released' => '1955',
        'height' => '220px',
    ],
    'Emerald Echoes' => [
        'id' => '67890',
        'author' => 'Henry Wordsmith',
        'color' => 'Green',
        'genre' => 'Romance',
        'released' => '1912',
        'height' => '240px',
    ],
    'Golden Key' => [
        'id' => '89797',
        'author' => 'Isabel Storyteller',
        'color' => 'Yellow',
        'genre' => 'Adventure',
        'released' => '1992',
        'height' => '248px',
    ],
    'Sapphire Shadows' => [
        'id' => '23556',
        'author' => 'Jack Author',
        'color' => 'Blue',
        'genre' => 'Thriller',
        'released' => '1998',
        'height' => '248px',
    ],
    'Scarlet Secrets' => [
        'id' => '56341',
        'author' => 'Karine Novelist',
        'color' => 'Red',
        'genre' => 'Mystery',
        'released' => '2008',
        'height' => '242px',
    ],
    'Bronze Blade' => [
        'id' => '32545',
        'author' => 'Liam Writer',
        'color' => 'teal',
        'genre' => 'Historical Fiction',
        'released' => '2010',
        'height' => '225px',
    ],
    'Violet Vendetta' => [
        'id' => '93275',
        'author' => 'Mia Wordsmith',
        'color' => 'Purple',
        'genre' => 'Crime',
        'released' => '1988',
        'height' => '220px',
    ],
    'Enchanted Forest' => [
        'id' => '23564',
        'author' => 'Nathan Storyteller',
        'color' => 'Green',
        'genre' => 'Fantasy',
        'released' => '1988',
        'height' => '241px',
    ],
    'Ruby Redem' => [
        'id' => '12456',
        'author' => 'Olivia Author',
        'color' => 'Red',
        'genre' => 'Romance',
        'released' => '1942',
        'height' => '237px',
    ],
    'Midnight Murders' => [
        'id' => '32675',
        'author' => 'Patrick Novelist',
        'color' => 'navy',
        'genre' => 'Mystery',
        'released' => '2002',
        'height' => '244px',
    ],
    'Aqua Odyssey' => [
        'id' => '65488',
        'author' => 'Quincy Writer',
        'color' => 'Aqua',
        'genre' => 'Adventure',
        'released' => '2014',
        'height' => '244px',
    ],
    'Copper Chronicles' => [
        'id' => '23298',
        'author' => 'Rachel Wordsmith',
        'color' => 'violet',
        'genre' => 'Fantasy',
        'released' => '2020',
        'height' => '223px',
    ],
    'Topaz Treasures' => [
        'id' => '53489',
        'author' => 'Samuel Storyteller',
        'color' => 'Orange',
        'genre' => 'Adventure',
        'released' => '2019',
        'height' => '210px',
    ]
];
